apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-k8s-test
spec:
  template:
    spec:
      containers:
        - name: k8s-test
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node"]
          args: ["src/k8s-test.js"]
      restartPolicy: Never