apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongoServiceName }} 
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: {{ .Values.mongo.port }}
      targetPort: {{ .Values.mongo.port }}
  type: ClusterIP