apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.mongoServiceName }} # Important: This name is used by k8s-test.js
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: {{ .Values.mongo.port }}
      targetPort: {{ .Values.mongo.port }}
  type: ClusterIP
