# k8s-test-mongo-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-k8s-test
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-mongodb
          image: busybox
          command: ['sh', '-c', 'until nc -z {{ .Values.mongo.mongoServiceName }} {{ .Values.mongo.port }}; do echo waiting for mongodb; sleep 45; done;']
      containers:
        - name: k8s-test
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{ .Values.test.command }}
          args: {{ .Values.test.args }}
          env:
            - name: MONGO_SERVICE_NAME
              value: "{{ .Values.mongo.mongoServiceName }}"
      restartPolicy: Never